Updatijg cast and scribe.  Work in progress

diff --git a/cast b/cast
--- a/cast
+++ b/cast
@@ -1,4 +1,25 @@
 #!/usr/bin/env zsh
+# will eventually add lines to only happen when debugging right now always on
+set +x 
+# ─────────────────────────────────────────────────────────────
+# If no subcommand is given, print a little help/usage and exit
+if [[ $# -eq 0 ]]; then
+  cat <<EOF
+Usage: cast <spell>
+
+Run “cast spell to install a spell from grimoire."
+EOF
+  exit 0
+fi
+
+# Require root
+if [[ "$EUID" -ne 0 ]]; then
+  echo "Error: This command must be run as root or with sudo." >&2
+  exit 1
+fi
+
+
+
 # Resolve grimoire paths
 if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
   echo "Usage: cast <spell>
@@ -17,7 +38,6 @@ else
 fi
 GRIMOIRE_PATH_GLOBAL="/etc/neosorcery/grimoire"
 
-#!/usr/bin/env zsh
 [[ -f /etc/sorcery.conf ]] && source /etc/sorcery.conf
 [[ -f "$HOME/.sorcery/sorcery.local.conf" ]] && source "$HOME/.sorcery/sorcery.local.conf"
 
